# Generated by Django 2.1.5 on 2019-02-18 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190215_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 2, 18)),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_date_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 2, 18)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 10, 8, 51, 405269, tzinfo=utc), verbose_name='date_joined'),
        ),
    ]
